
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/tododb?createDatabaseIfNotExist=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Ntdung0829@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

server.port=${PORT:8080}
